.Id $Id: owcimomd.8.fb,v 1.1.1.1 2002/03/01 16:58:14 nuffer Exp $
.TH owcimomd 8 "September 2001" owcimomd "OpenWBEM Framework"
.SH NAME
owcimomd \- The OpenWBEM CIM Object Manager daemon
.SH SYNOPSIS
.B owcimomd
.RB [ \-d ]
.RB [ \-c 
.IR CONFIGURATION_FILE ]
.SH DESCRIPTION
.B owcimomd
This is the OpenWBEM CIMOM.  It's configuration is contained in
.I openwbem.conf 
.
.PP
.SH OPTIONS
.TP 8
.B \-d 
Do not detach from the terminal, set the log level to debug, and send logging
information to the terminal (as well as the log location specified in 
.I openwbem.conf
)
.TP 8
.BI \-c " CONFIGURATION_FILE"
The path to the configuration file.  If this parameter is omitted, 
.B owcimomd
tries for the default: 
.I /usr/local/etc/openwbem/openwbem.conf
.SH FILES
.I openwbem.conf
The configuration file used by owcimomd.
.PP
.SH "SEE ALSO"
owmofc(1), owdigestgenpass(8), owexecwql(1)
.SH BUGS
None known at this time.
