#pragma namespace("root/secondaryinstanceprovidertest")

Qualifier Key : boolean = false, 
    Scope(property, reference), 
    Flavor(DisableOverride);

class SecondaryInstanceTest
{
	[Key] String key;
	String prop2;
	String prop3;
	String prop4;
};

instance of SecondaryInstanceTest
{
	key = "1";
	prop2 = "p2";
};

instance of SecondaryInstanceTest
{
	key = "2";
	prop2 = "p2";
};

