/* automatically generated */
#ifndef __SRC_COMMON_OW_CONFIG_H
#define __SRC_COMMON_OW_CONFIG_H 1
 
/* ./src/common/OW_config.h. Generated automatically at end of configure. */
/* config.h.  Generated by configure.  */
/* config.h.in.  Generated from configure.in by autoheader.  */
/*******************************************************************************
* Copyright (C) 2001-3 Vintela, Inc. All rights reserved.
*
* Redistribution and use in source and binary forms, with or without
* modification, are permitted provided that the following conditions are met:
*
*  - Redistributions of source code must retain the above copyright notice,
*    this list of conditions and the following disclaimer.
*
*  - Redistributions in binary form must reproduce the above copyright notice,
*    this list of conditions and the following disclaimer in the documentation
*    and/or other materials provided with the distribution.
*
*  - Neither the name of Vintela, Inc. nor the names of its
*    contributors may be used to endorse or promote products derived from this
*    software without specific prior written permission.
*
* THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS ``AS IS''
* AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
* IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE
* ARE DISCLAIMED. IN NO EVENT SHALL Vintela, Inc. OR THE CONTRIBUTORS
* BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR
* CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF
* SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS
* INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN
* CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE)
* ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE
* POSSIBILITY OF SUCH DAMAGE.
*******************************************************************************/

/**
 * @author Dan Nuffer
 */




/* autoconf set variables here */


/* The system has OpenSSL headers and libs */
#ifndef OW_HAVE_OPENSSL 
#define OW_HAVE_OPENSSL 1 
#endif

/* The system doesn't have OpenSSL */
/* #undef OW_NO_SSL */

/* Dirs from configure */
#ifndef OW_DEFAULT_SYSCONF_DIR 
#define OW_DEFAULT_SYSCONF_DIR "/usr/local/etc" 
#endif
#ifndef OW_DEFAULT_STATE_DIR 
#define OW_DEFAULT_STATE_DIR "/usr/local/var" 
#endif
#ifndef OW_DEFAULT_LIB_DIR 
#define OW_DEFAULT_LIB_DIR "/usr/local/lib" 
#endif
#ifndef OW_DEFAULT_LIBEXEC_DIR 
#define OW_DEFAULT_LIBEXEC_DIR "/usr/local/libexec" 
#endif
#ifndef OW_PIDFILE_DIR 
#define OW_PIDFILE_DIR "/var/run" 
#endif

/* Either "" or the argument to --with-package-prefix */
#ifndef OW_PACKAGE_PREFIX 
#define OW_PACKAGE_PREFIX "" 
#endif

/* Defined if --enable-stack-trace was passed to configure */
/* #undef OW_ENABLE_STACK_TRACE_ON_EXCEPTIONS */

/* Defined if --enable-debug was passed to configure */
/* #undef OW_DEBUG */

/* Defined if --enable-profile was passed to configure */
/* #undef OW_PROFILE */

/* Defined if we are building gnu pthreads version */
#ifndef OW_USE_PTHREAD 
#define OW_USE_PTHREAD 1 
#endif

/* Defined if we want to use custom "new" operator to debug memory leaks */
/* #undef OW_DEBUG_MEMORY */

/* Define if we want to print "Entering"/"Leaving" <functionName> */
/* #undef OW_PRINT_FUNC_DEBUG */

/* Define if we want to check for NULL references and throw an exception */
#ifndef OW_CHECK_NULL_REFERENCES 
#define OW_CHECK_NULL_REFERENCES 1 
#endif

/* Define if we want to check for valid array indexing and throw an exception */
#ifndef OW_CHECK_ARRAY_INDEXING 
#define OW_CHECK_ARRAY_INDEXING 1 
#endif

/* Define if we want to build the perlIFC */
/* #undef OW_PERLIFC */

/* Define which one is the current platform */
#ifndef OW_GNU_LINUX 
#define OW_GNU_LINUX 1 
#endif
/* #undef OW_OPENUNIX */
/* #undef OW_SOLARIS */
/* #undef OW_OPENSERVER */
/* #undef OW_DARWIN */
/* #undef OW_HPUX */
/* #undef OW_FREEBSD */


/* #undef u_int8_t */
/* #undef u_int16_t */
/* #undef u_int32_t */
#ifndef OW_HAVE_SOCKLEN_T 
#define OW_HAVE_SOCKLEN_T 1 
#endif

#ifndef OW_HAVE_PTHREAD_MUTEXATTR_SETTYPE 
#define OW_HAVE_PTHREAD_MUTEXATTR_SETTYPE 1 
#endif
#ifndef OW_HAVE_PTHREAD_SPIN_LOCK 
#define OW_HAVE_PTHREAD_SPIN_LOCK 1 
#endif
#ifndef OW_HAVE_PTHREAD_BARRIER 
#define OW_HAVE_PTHREAD_BARRIER 1 
#endif
#ifndef OW_HAVE_PAM 
#define OW_HAVE_PAM 1 
#endif

/* Define if system has dlfcn.h */
#ifndef OW_USE_DL 
#define OW_USE_DL 1 
#endif
/* Define if system has shl_*() <dl.h> */
/* #undef OW_USE_SHL */
/* Define if a system has dyld.h (Mac OS X) */
/* #undef OW_USE_DYLD */

/* #undef OW_DISABLE_DIGEST */
/* #undef OW_DISABLE_ASSOCIATION_TRAVERSAL */
/* #undef OW_DISABLE_QUALIFIER_DECLARATION */
/* #undef OW_DISABLE_SCHEMA_MANIPULATION */
/* #undef OW_DISABLE_INSTANCE_MANIPULATION */
/* #undef OW_DISABLE_PROPERTY_OPERATIONS */
/* #undef OW_DISABLE_NAMESPACE_MANIPULATION */

/* Define to enable workarounds so we can work with valgrind */
/* #undef OW_VALGRIND_SUPPORT */

/* Define to enable workarounds for non-thread safe exception handling support */
/* #undef OW_NON_THREAD_SAFE_EXCEPTION_HANDLING */


/* Target OS is AIX */
/* #undef OW_AIX */

/* HP PA-RISC 2.0 architecture */
/* #undef OW_ARCH_HPPA20 */

/* PowerPC architecture */
/* #undef OW_ARCH_PPC */

/* SPARC architecture */
/* #undef OW_ARCH_SPARC */

/* Unknown architecture */
/* #undef OW_ARCH_UNKNOWN */

/* Intel x86 architecture */
#ifndef OW_ARCH_X86 
#define OW_ARCH_X86 1 
#endif

/* x86-64 architecture */
/* #undef OW_ARCH_X86_64 */

/* Target OS is DARWIN */
/* #undef OW_DARWIN */

/* "The bin dir" */
#ifndef OW_DEFAULT_BIN_DIR 
#define OW_DEFAULT_BIN_DIR "/usr/local/bin" 
#endif

/* "The sbin dir" */
#ifndef OW_DEFAULT_SBIN_DIR 
#define OW_DEFAULT_SBIN_DIR "/usr/local/sbin" 
#endif

/* Enable db4 repository */
/* #undef OW_ENABLE_DB4_REPOSITORY */

/* Where false is. */
#ifndef OW_FALSE_PATHNAME 
#define OW_FALSE_PATHNAME "/bin/false" 
#endif

/* Number of args to gethostbyname_r() */
#ifndef OW_GETHOSTBYNAME_R_ARGUMENTS 
#define OW_GETHOSTBYNAME_R_ARGUMENTS 6 
#endif

/* Define to 1 if getopt and unistd conflict */
/* #undef OW_GETOPT_AND_UNISTD_CONFLICT */

/* Define to 1 if you have the <alloca.h> header file. */
#ifndef OW_HAVE_ALLOCA_H 
#define OW_HAVE_ALLOCA_H 1 
#endif

/* Define to 1 if you have the `asctime_r' function. */
#ifndef OW_HAVE_ASCTIME_R 
#define OW_HAVE_ASCTIME_R 1 
#endif

/* Define to 1 if you have the `backtrace' function. */
#ifndef OW_HAVE_BACKTRACE 
#define OW_HAVE_BACKTRACE 1 
#endif

/* Define to 1 if you have the <byteswap.h> header file. */
#ifndef OW_HAVE_BYTESWAP_H 
#define OW_HAVE_BYTESWAP_H 1 
#endif

/* Define to 1 if the C++ compiler supports the C99 __func__ */
#ifndef OW_HAVE_C99_UUFUNCUU 
#define OW_HAVE_C99_UUFUNCUU 1 
#endif

/* Define to 1 if you have the <cxxabi.h> header file. */
#ifndef OW_HAVE_CXXABI_H 
#define OW_HAVE_CXXABI_H 1 
#endif

/* Define to 1 if you have the declaration of `sys_siglist', and to 0 if you
   don't. */
#ifndef OW_HAVE_DECL_SYS_SIGLIST 
#define OW_HAVE_DECL_SYS_SIGLIST 1 
#endif

/* Define to 1 if you have the <dirent.h> header file. */
#ifndef OW_HAVE_DIRENT_H 
#define OW_HAVE_DIRENT_H 1 
#endif

/* Define to 1 if you have the `dlopen' function. */
/* #undef OW_HAVE_DLOPEN */

/* Define to 1 if you don't have `vprintf' but do have `_doprnt.' */
/* #undef OW_HAVE_DOPRNT */

/* Define to 1 if you have the <ext/hash_map> header file. */
#ifndef OW_HAVE_EXT_HASH_MAP 
#define OW_HAVE_EXT_HASH_MAP 1 
#endif

/* Define to 1 if you have the <fcntl.h> header file. */
#ifndef OW_HAVE_FCNTL_H 
#define OW_HAVE_FCNTL_H 1 
#endif

/* Have gethostbyname_r() */
#ifndef OW_HAVE_GETHOSTBYNAME_R 
#define OW_HAVE_GETHOSTBYNAME_R 1 
#endif

/* Define to 1 if you have the <getopt.h> header file. */
#ifndef OW_HAVE_GETOPT_H 
#define OW_HAVE_GETOPT_H 1 
#endif

/* Define to 1 if you have the `getopt_long' function. */
#ifndef OW_HAVE_GETOPT_LONG 
#define OW_HAVE_GETOPT_LONG 1 
#endif

/* Define to 1 if you have the `getpagesize' function. */
#ifndef OW_HAVE_GETPAGESIZE 
#define OW_HAVE_GETPAGESIZE 1 
#endif

/* Define to 1 if you have the `getpwnam_r' function. */
#ifndef OW_HAVE_GETPWNAM_R 
#define OW_HAVE_GETPWNAM_R 1 
#endif

/* Define to 1 if you have the `getpwuid_r' function. */
#ifndef OW_HAVE_GETPWUID_R 
#define OW_HAVE_GETPWUID_R 1 
#endif

/* Define to 1 if you have the `gettimeofday' function. */
#ifndef OW_HAVE_GETTIMEOFDAY 
#define OW_HAVE_GETTIMEOFDAY 1 
#endif

/* Define to 1 if you have the `gmtime_r' function. */
#ifndef OW_HAVE_GMTIME_R 
#define OW_HAVE_GMTIME_R 1 
#endif

/* Define to 1 if you have the <grp.h> header file. */
#ifndef OW_HAVE_GRP_H 
#define OW_HAVE_GRP_H 1 
#endif

/* Define to 1 if you have the <hash_map> header file. */
/* #undef OW_HAVE_HASH_MAP */

/* Define to 1 if you have the <inttypes.h> header file. */
#ifndef OW_HAVE_INTTYPES_H 
#define OW_HAVE_INTTYPES_H 1 
#endif

/* Define to 1 if you have the <istream> header file. */
#ifndef OW_HAVE_ISTREAM 
#define OW_HAVE_ISTREAM 1 
#endif

/* Define to 1 if you have the <istream.h> header file. */
#ifndef OW_HAVE_ISTREAM_H 
#define OW_HAVE_ISTREAM_H 1 
#endif

/* Define to 1 if you have the <limits.h> header file. */
#ifndef OW_HAVE_LIMITS_H 
#define OW_HAVE_LIMITS_H 1 
#endif

/* Define to 1 if you have the `localtime_r' function. */
#ifndef OW_HAVE_LOCALTIME_R 
#define OW_HAVE_LOCALTIME_R 1 
#endif

/* Define to 1 if you have the <memory.h> header file. */
#ifndef OW_HAVE_MEMORY_H 
#define OW_HAVE_MEMORY_H 1 
#endif

/* Define to 1 if you have the `mkstemp' function. */
#ifndef OW_HAVE_MKSTEMP 
#define OW_HAVE_MKSTEMP 1 
#endif

/* Define to 1 if you have a working `mmap' system call. */
#ifndef OW_HAVE_MMAP 
#define OW_HAVE_MMAP 1 
#endif

/* Define to 1 if you have the `nanosleep' function. */
#ifndef OW_HAVE_NANOSLEEP 
#define OW_HAVE_NANOSLEEP 1 
#endif

/* Define to 1 if you have the <netinet/in.h> header file. */
#ifndef OW_HAVE_NETINET_IN_H 
#define OW_HAVE_NETINET_IN_H 1 
#endif

/* Define to 1 if you have the `NSLinkModule' function. */
/* #undef OW_HAVE_NSLINKMODULE */

/* Define to 1 if you have the <ostream> header file. */
#ifndef OW_HAVE_OSTREAM 
#define OW_HAVE_OSTREAM 1 
#endif

/* Define to 1 if you have the <ostream.h> header file. */
#ifndef OW_HAVE_OSTREAM_H 
#define OW_HAVE_OSTREAM_H 1 
#endif

/* Define to 1 if you have the <pam/pam_appl.h> header file. */
/* #undef OW_HAVE_PAM_PAM_APPL_H */

/* Define to 1 if you have the <pam/pam_misc.h> header file. */
/* #undef OW_HAVE_PAM_PAM_MISC_H */

/* pthread_atfork() exists */
/* #undef OW_HAVE_PTHREAD_ATFORK */

/* Define to 1 if you have the <pthread.h> header file. */
#ifndef OW_HAVE_PTHREAD_H 
#define OW_HAVE_PTHREAD_H 1 
#endif

/* Define to 1 if you have the `pthread_kill_other_threads_np' function. */
/* #undef OW_HAVE_PTHREAD_KILL_OTHER_THREADS_NP */

/* Define to 1 if you have the <pwd.h> header file. */
#ifndef OW_HAVE_PWD_H 
#define OW_HAVE_PWD_H 1 
#endif

/* Define to 1 if you have the `random' function. */
#ifndef OW_HAVE_RANDOM 
#define OW_HAVE_RANDOM 1 
#endif

/* Define to 1 if you have the `sched_yield' function. */
#ifndef OW_HAVE_SCHED_YIELD 
#define OW_HAVE_SCHED_YIELD 1 
#endif

/* Define to 1 if you have the <security/pam_appl.h> header file. */
#ifndef OW_HAVE_SECURITY_PAM_APPL_H 
#define OW_HAVE_SECURITY_PAM_APPL_H 1 
#endif

/* Define to 1 if you have the <security/pam_misc.h> header file. */
#ifndef OW_HAVE_SECURITY_PAM_MISC_H 
#define OW_HAVE_SECURITY_PAM_MISC_H 1 
#endif

/* Define to 1 if you have the `setrlimit' function. */
#ifndef OW_HAVE_SETRLIMIT 
#define OW_HAVE_SETRLIMIT 1 
#endif

/* Define to 1 if the system has the type `sighandler_t'. */
#ifndef OW_HAVE_SIGHANDLER_T 
#define OW_HAVE_SIGHANDLER_T 1 
#endif

/* Define to 1 if `si_fd' is member of `siginfo_t'. */
#ifndef OW_HAVE_SIGINFO_T_SI_FD 
#define OW_HAVE_SIGINFO_T_SI_FD 1 
#endif

/* Define to 1 if the system has the type `sigval'. */
/* #undef OW_HAVE_SIGVAL */

/* Define to 1 if the system has the type `sigval_t'. */
/* #undef OW_HAVE_SIGVAL_T */

/* Define to 1 if `sigval_int' is member of `SIGVAL_TYPE'. */
/* #undef OW_HAVE_SIGVAL_TYPE_SIGVAL_INT */

/* Define to 1 if `sival_int' is member of `SIGVAL_TYPE'. */
#ifndef OW_HAVE_SIGVAL_TYPE_SIVAL_INT 
#define OW_HAVE_SIGVAL_TYPE_SIVAL_INT 1 
#endif

/* Define to 1 if you have the <slp.h> header file. */
#ifndef OW_HAVE_SLP_H 
#define OW_HAVE_SLP_H 1 
#endif

/* Define to 1 if you have the `snprintf' function. */
#ifndef OW_HAVE_SNPRINTF 
#define OW_HAVE_SNPRINTF 1 
#endif

/* Define to 1 if you have the `srandom' function. */
#ifndef OW_HAVE_SRANDOM 
#define OW_HAVE_SRANDOM 1 
#endif

/* Define to 1 if you have the <stdint.h> header file. */
#ifndef OW_HAVE_STDINT_H 
#define OW_HAVE_STDINT_H 1 
#endif

/* Define to 1 if you have the <stdlib.h> header file. */
#ifndef OW_HAVE_STDLIB_H 
#define OW_HAVE_STDLIB_H 1 
#endif

/* Define to 1 if you have the <streambuf> header file. */
#ifndef OW_HAVE_STREAMBUF 
#define OW_HAVE_STREAMBUF 1 
#endif

/* Define to 1 if you have the <streambuf.h> header file. */
#ifndef OW_HAVE_STREAMBUF_H 
#define OW_HAVE_STREAMBUF_H 1 
#endif

/* Define to 1 if you have the `strerror' function. */
#ifndef OW_HAVE_STRERROR 
#define OW_HAVE_STRERROR 1 
#endif

/* Define to 1 if you have the <strings.h> header file. */
#ifndef OW_HAVE_STRINGS_H 
#define OW_HAVE_STRINGS_H 1 
#endif

/* Define to 1 if you have the <string.h> header file. */
#ifndef OW_HAVE_STRING_H 
#define OW_HAVE_STRING_H 1 
#endif

/* Define to 1 if you have the <stropts.h> header file. */
#ifndef OW_HAVE_STROPTS_H 
#define OW_HAVE_STROPTS_H 1 
#endif

/* Define to 1 if you have the `strsignal' function. */
#ifndef OW_HAVE_STRSIGNAL 
#define OW_HAVE_STRSIGNAL 1 
#endif

/* Define to 1 if you have the `strtof' function. */
#ifndef OW_HAVE_STRTOF 
#define OW_HAVE_STRTOF 1 
#endif

/* Define to 1 if you have the `strtoll' function. */
#ifndef OW_HAVE_STRTOLL 
#define OW_HAVE_STRTOLL 1 
#endif

/* Define to 1 if you have the `strtoull' function. */
#ifndef OW_HAVE_STRTOULL 
#define OW_HAVE_STRTOULL 1 
#endif

/* Define to 1 if the system has the type `struct sigval'. */
/* #undef OW_HAVE_STRUCT_SIGVAL */

/* Define to 1 if the system has the type `struct sigval_t'. */
/* #undef OW_HAVE_STRUCT_SIGVAL_T */

/* Define to 1 if `st_blksize' is member of `struct stat'. */
#ifndef OW_HAVE_STRUCT_STAT_ST_BLKSIZE 
#define OW_HAVE_STRUCT_STAT_ST_BLKSIZE 1 
#endif

/* Define to 1 if your `struct stat' has `st_blksize'. Deprecated, use
   `HAVE_STRUCT_STAT_ST_BLKSIZE' instead. */
#ifndef OW_HAVE_ST_BLKSIZE 
#define OW_HAVE_ST_BLKSIZE 1 
#endif

/* Define to 1 if you have the <sys/cdefs.h> header file. */
#ifndef OW_HAVE_SYS_CDEFS_H 
#define OW_HAVE_SYS_CDEFS_H 1 
#endif

/* Define to 1 if you have the <sys/epoll.h> header file. */
#ifndef OW_HAVE_SYS_EPOLL_H 
#define OW_HAVE_SYS_EPOLL_H 1 
#endif

/* Define to 1 if you have the <sys/file.h> header file. */
#ifndef OW_HAVE_SYS_FILE_H 
#define OW_HAVE_SYS_FILE_H 1 
#endif

/* Define to 1 if you have the <sys/int_types.h> header file. */
/* #undef OW_HAVE_SYS_INT_TYPES_H */

/* Define to 1 if you have the <sys/param.h> header file. */
#ifndef OW_HAVE_SYS_PARAM_H 
#define OW_HAVE_SYS_PARAM_H 1 
#endif

/* Define to 1 if you have the <sys/poll.h> header file. */
#ifndef OW_HAVE_SYS_POLL_H 
#define OW_HAVE_SYS_POLL_H 1 
#endif

/* Define to 1 if you have the <sys/queue.h> header file. */
#ifndef OW_HAVE_SYS_QUEUE_H 
#define OW_HAVE_SYS_QUEUE_H 1 
#endif

/* Define to 1 if you have the <sys/resource.h> header file. */
#ifndef OW_HAVE_SYS_RESOURCE_H 
#define OW_HAVE_SYS_RESOURCE_H 1 
#endif

/* Define to 1 if you have the <sys/select.h> header file. */
#ifndef OW_HAVE_SYS_SELECT_H 
#define OW_HAVE_SYS_SELECT_H 1 
#endif

/* Define to 1 if you have the <sys/socket.h> header file. */
#ifndef OW_HAVE_SYS_SOCKET_H 
#define OW_HAVE_SYS_SOCKET_H 1 
#endif

/* Define to 1 if you have the <sys/sockio.h> header file. */
/* #undef OW_HAVE_SYS_SOCKIO_H */

/* Define to 1 if you have the <sys/stat.h> header file. */
#ifndef OW_HAVE_SYS_STAT_H 
#define OW_HAVE_SYS_STAT_H 1 
#endif

/* Define to 1 if you have the <sys/time.h> header file. */
#ifndef OW_HAVE_SYS_TIME_H 
#define OW_HAVE_SYS_TIME_H 1 
#endif

/* Define to 1 if you have the <sys/types.h> header file. */
#ifndef OW_HAVE_SYS_TYPES_H 
#define OW_HAVE_SYS_TYPES_H 1 
#endif

/* Define to 1 if you have the <sys/un.h> header file. */
#ifndef OW_HAVE_SYS_UN_H 
#define OW_HAVE_SYS_UN_H 1 
#endif

/* Define to 1 if you have the <sys/wait.h> header file. */
#ifndef OW_HAVE_SYS_WAIT_H 
#define OW_HAVE_SYS_WAIT_H 1 
#endif

/* Define to 1 if you have the `timegm' function. */
#ifndef OW_HAVE_TIMEGM 
#define OW_HAVE_TIMEGM 1 
#endif

/* Define to 1 if the system has the type `union sigval'. */
#ifndef OW_HAVE_UNION_SIGVAL 
#define OW_HAVE_UNION_SIGVAL 1 
#endif

/* Define to 1 if the system has the type `union sigval_t'. */
/* #undef OW_HAVE_UNION_SIGVAL_T */

/* Define to 1 if you have the <unistd.h> header file. */
#ifndef OW_HAVE_UNISTD_H 
#define OW_HAVE_UNISTD_H 1 
#endif

/* Define to 1 if the C++ compiler supports __PRETTY_FUNCTION__ */
#ifndef OW_HAVE_UUPRETTY_FUNCTIONUU 
#define OW_HAVE_UUPRETTY_FUNCTIONUU 1 
#endif

/* Define to 1 if you have the `vprintf' function. */
#ifndef OW_HAVE_VPRINTF 
#define OW_HAVE_VPRINTF 1 
#endif

/* Define to 1 if you have the <zlib.h> header file. */
#ifndef OW_HAVE_ZLIB_H 
#define OW_HAVE_ZLIB_H 1 
#endif

/* Define to 1 if <inttypes.h> defines PRIu32 and PRIx32. */
/* #undef OW_INTTYPES_H_DEFINES_PRI */

/* Define to 1 if <inttypes.h> does not define PRIu32 or PRIx32. */
#ifndef OW_INTTYPES_H_DOES_NOT_DEFINE_PRI 
#define OW_INTTYPES_H_DOES_NOT_DEFINE_PRI 1 
#endif

/* Target OS is NetWare */
/* #undef OW_NETWARE */

/* OpenWBEM Library Version */
#ifndef OW_OPENWBEM_LIBRARY_VERSION 
#define OW_OPENWBEM_LIBRARY_VERSION 4 
#endif

/* OpenWBEM Major Version */
#ifndef OW_OPENWBEM_MAJOR_VERSION 
#define OW_OPENWBEM_MAJOR_VERSION 3 
#endif

/* OpenWBEM Micro Version */
#ifndef OW_OPENWBEM_MICRO_VERSION 
#define OW_OPENWBEM_MICRO_VERSION 3 
#endif

/* OpenWBEM Minor Version */
#ifndef OW_OPENWBEM_MINOR_VERSION 
#define OW_OPENWBEM_MINOR_VERSION 2 
#endif

/* OpenWBEM Version */
#ifndef OW_OPENWBEM_VERSION 
#define OW_OPENWBEM_VERSION (3*10000 + 2*100 + 3) 
#endif

/* Name of package */
#ifndef OW_PACKAGE 
#define OW_PACKAGE "openwbem" 
#endif

/* Define to the address where bug reports for this package should be sent. */
#ifndef OW_PACKAGE_BUGREPORT 
#define OW_PACKAGE_BUGREPORT "openwbem-public@lists.sourceforge.net" 
#endif

/* Define to the full name of this package. */
#ifndef OW_PACKAGE_NAME 
#define OW_PACKAGE_NAME "OpenWBEM" 
#endif

/* Define to the full name and version of this package. */
#ifndef OW_PACKAGE_STRING 
#define OW_PACKAGE_STRING "OpenWBEM 3.2.3" 
#endif

/* Define to the one symbol short name of this package. */
#ifndef OW_PACKAGE_TARNAME 
#define OW_PACKAGE_TARNAME "openwbem" 
#endif

/* Define to the version of this package. */
#ifndef OW_PACKAGE_VERSION 
#define OW_PACKAGE_VERSION "3.2.3" 
#endif

/* The sigval type */
#ifndef OW_SIGVAL_TYPE 
#define OW_SIGVAL_TYPE union sigval 
#endif

/* The size of a `char', as computed by sizeof. */
#ifndef OW_SIZEOF_CHAR 
#define OW_SIZEOF_CHAR 1 
#endif

/* The size of a `char *', as computed by sizeof. */
#ifndef OW_SIZEOF_CHAR_P 
#define OW_SIZEOF_CHAR_P 4 
#endif

/* The size of a `double', as computed by sizeof. */
#ifndef OW_SIZEOF_DOUBLE 
#define OW_SIZEOF_DOUBLE 8 
#endif

/* The size of a `float', as computed by sizeof. */
#ifndef OW_SIZEOF_FLOAT 
#define OW_SIZEOF_FLOAT 4 
#endif

/* The size of a `int', as computed by sizeof. */
#ifndef OW_SIZEOF_INT 
#define OW_SIZEOF_INT 4 
#endif

/* The size of a `long double', as computed by sizeof. */
#ifndef OW_SIZEOF_LONG_DOUBLE 
#define OW_SIZEOF_LONG_DOUBLE 12 
#endif

/* The size of a `long int', as computed by sizeof. */
#ifndef OW_SIZEOF_LONG_INT 
#define OW_SIZEOF_LONG_INT 4 
#endif

/* The size of a `long long int', as computed by sizeof. */
#ifndef OW_SIZEOF_LONG_LONG_INT 
#define OW_SIZEOF_LONG_LONG_INT 8 
#endif

/* The size of a `pthread_t', as computed by sizeof. */
#ifndef OW_SIZEOF_PTHREAD_T 
#define OW_SIZEOF_PTHREAD_T 4 
#endif

/* The size of a `short int', as computed by sizeof. */
#ifndef OW_SIZEOF_SHORT_INT 
#define OW_SIZEOF_SHORT_INT 2 
#endif

/* Static services are enabled */
/* #undef OW_STATIC_SERVICES */

/* Define to 1 if you have the ANSI C header files. */
#ifndef OW_STDC_HEADERS 
#define OW_STDC_HEADERS 1 
#endif

/* Threads run as the authenticated user */
/* #undef OW_THREADS_RUN_AS_USER */

/* Where true is. */
#ifndef OW_TRUE_PATHNAME 
#define OW_TRUE_PATHNAME "/bin/true" 
#endif

/* Fake libraries are enabled */
/* #undef OW_USE_FAKE_LIBS */

/* Version number of package */
#ifndef OW_VERSION 
#define OW_VERSION "3.2.3" 
#endif

/* Define to 1 if WIFEXITED and WEXITSTATUS require wait.h */
#ifndef OW_WIFEXITED_NEEDS_WAIT_H 
#define OW_WIFEXITED_NEEDS_WAIT_H 1 
#endif

/* Define to 1 if your processor stores words with the most significant byte
   first (like Motorola and SPARC, unlike Intel and VAX). */
/* #undef OW_WORDS_BIGENDIAN */

/* Define to 1 if `lex' declares `yytext' as a `char *' by default, not a
   `char[]'. */
#ifndef OW_YYTEXT_POINTER 
#define OW_YYTEXT_POINTER 1 
#endif

/* Define to `long' if <sys/types.h> does not define. */
/* #undef off_t */

/* Define to `unsigned' if <sys/types.h> does not define. */
/* #undef size_t */

/* Define to `uint16_t' if <sys/types.h> does not define. */
/* #undef u_int16_t */

/* Define to `uint32_t' if <sys/types.h> does not define. */
/* #undef u_int32_t */

/* Define to `uint8_t' if <sys/types.h> does not define. */
/* #undef u_int8_t */

/* end of autoconf set vars */

/**
 * The OW_DEPRECATED macro can be used to trigger compile-time warnings
 * with gcc >= 3.2 when deprecated functions are used.
 *
 * For non-inline functions, the macro is used at the very end of the
 * function declaration, right before the semicolon, unless it's pure
 * virtual:
 *
 * int deprecatedFunc() const OW_DEPRECATED;
 * virtual int deprecatedPureVirtualFunc() const OW_DEPRECATED = 0;
 *
 * Functions which are implemented inline are handled differently:
 * the OW_DEPRECATED macro is used at the front, right before the return
 * type, but after "static" or "virtual":
 *
 * OW_DEPRECATED void deprecatedFuncA() { .. }
 * virtual OW_DEPRECATED int deprecatedFuncB() { .. }
 * static OW_DEPRECATED bool deprecatedFuncC() { .. }
 *
 * You can also mark whole structs or classes as deprecated, by inserting the
 * OW_DEPRECATED macro after the struct/class keyword, but before the
 * name of the struct/class:
 *
 * class OW_DEPRECATED DeprecatedClass { };
 * struct OW_DEPRECATED DeprecatedStruct { };
 *
 * However, deprecating a struct/class doesn't create a warning for gcc
 * versions <= 3.3 (haven't tried 3.4 yet).  If you want to deprecate a class,
 * also deprecate all member functions as well (which will cause warnings).
 *
 */
#if __GNUC__ - 0 > 3 || (__GNUC__ - 0 == 3 && __GNUC_MINOR__ - 0 >= 2)
#ifndef OW_DEPRECATED 
#define OW_DEPRECATED __attribute__ ((deprecated)) 
#endif
#else
#ifndef OW_DEPRECATED 
#define OW_DEPRECATED 
#endif
#endif



#ifdef OW_WIN32
#ifndef OW_EXPORT 
#define OW_EXPORT __declspec(dllexport) 
#endif
#ifndef OW_IMPORT 
#define OW_IMPORT __declspec(dllimport) 
#endif
#else
#ifndef OW_EXPORT 
#define OW_EXPORT 
#endif
#ifndef OW_IMPORT 
#define OW_IMPORT 
#endif
#endif

#ifdef OW_COMMON_BUILD
#ifndef OW_COMMON_API 
#define OW_COMMON_API OW_EXPORT 
#endif
#else
#ifndef OW_COMMON_API 
#define OW_COMMON_API OW_IMPORT 
#endif
#endif

#ifdef OW_XML_BUILD
#ifndef OW_XML_API 
#define OW_XML_API OW_EXPORT 
#endif
#else
#ifndef OW_XML_API 
#define OW_XML_API OW_IMPORT 
#endif
#endif

#ifdef OW_MOF_BUILD
#ifndef OW_MOF_API 
#define OW_MOF_API OW_EXPORT 
#endif
#else
#ifndef OW_MOF_API 
#define OW_MOF_API OW_IMPORT 
#endif
#endif

#ifdef OW_HTTP_BUILD
#ifndef OW_HTTP_API 
#define OW_HTTP_API OW_EXPORT 
#endif
#else
#ifndef OW_HTTP_API 
#define OW_HTTP_API OW_IMPORT 
#endif
#endif

#ifdef OW_HTTPSVC_BUILD
#ifndef OW_HTTPSVC_API 
#define OW_HTTPSVC_API OW_EXPORT 
#endif
#else
#ifndef OW_HTTPSVC_API 
#define OW_HTTPSVC_API OW_IMPORT 
#endif
#endif

#ifdef OW_LISTENER_BUILD
#ifndef OW_LISTENER_API 
#define OW_LISTENER_API OW_EXPORT 
#endif
#else
#ifndef OW_LISTENER_API 
#define OW_LISTENER_API OW_IMPORT 
#endif
#endif


#ifdef OW_CLIENT_BUILD
#ifndef OW_CLIENT_API 
#define OW_CLIENT_API OW_EXPORT 
#endif
#else
#ifndef OW_CLIENT_API 
#define OW_CLIENT_API OW_IMPORT 
#endif
#endif

#ifdef OW_DB_BUILD
#ifndef OW_DB_API 
#define OW_DB_API OW_EXPORT 
#endif
#else
#ifndef OW_DB_API 
#define OW_DB_API OW_IMPORT 
#endif
#endif

#ifdef OW_REPHDB_BUILD
#ifndef OW_HDB_API 
#define OW_HDB_API OW_EXPORT 
#endif
#else
#ifndef OW_HDB_API 
#define OW_HDB_API OW_IMPORT 
#endif
#endif

#ifdef OW_WQL_BUILD
#ifndef OW_WQL_API 
#define OW_WQL_API OW_EXPORT 
#endif
#else
#ifndef OW_WQL_API 
#define OW_WQL_API OW_IMPORT 
#endif
#endif

#ifdef OW_WQLCOMMON_BUILD
#ifndef OW_WQLCOMMON_API 
#define OW_WQLCOMMON_API OW_EXPORT 
#endif
#else
#ifndef OW_WQLCOMMON_API 
#define OW_WQLCOMMON_API OW_IMPORT 
#endif
#endif

#ifdef OW_PROVIDER_BUILD
#ifndef OW_PROVIDER_API 
#define OW_PROVIDER_API OW_EXPORT 
#endif
#else
#ifndef OW_PROVIDER_API 
#define OW_PROVIDER_API OW_IMPORT 
#endif
#endif

#ifdef OW_CPPPROVIFC_BUILD
#ifndef OW_CPPPROVIFC_API 
#define OW_CPPPROVIFC_API OW_EXPORT 
#endif
#else
#ifndef OW_CPPPROVIFC_API 
#define OW_CPPPROVIFC_API OW_IMPORT 
#endif
#endif

#ifdef OW_CIMOMSERVER_BUILD
#ifndef OW_CIMOMSERVER_API 
#define OW_CIMOMSERVER_API OW_EXPORT 
#endif
#else
#ifndef OW_CIMOMSERVER_API 
#define OW_CIMOMSERVER_API OW_IMPORT 
#endif
#endif

#ifdef OW_CIMOMCOMMON_BUILD
#ifndef OW_CIMOMCOMMON_API 
#define OW_CIMOMCOMMON_API OW_EXPORT 
#endif
#else
#ifndef OW_CIMOMCOMMON_API 
#define OW_CIMOMCOMMON_API OW_IMPORT 
#endif
#endif

#ifdef OW_INDICATIONSERVER_BUILD
#ifndef OW_INDICATIONSERVER_API 
#define OW_INDICATIONSERVER_API OW_EXPORT 
#endif
#else
#ifndef OW_INDICATIONSERVER_API 
#define OW_INDICATIONSERVER_API OW_IMPORT 
#endif
#endif

#ifdef OW_INDICATIONREPLAYER_BUILD
#ifndef OW_INDICATIONREPLAYER_API 
#define OW_INDICATIONREPLAYER_API OW_EXPORT 
#endif
#else
#ifndef OW_INDICATIONREPLAYER_API 
#define OW_INDICATIONREPLAYER_API OW_IMPORT 
#endif
#endif

#ifdef OW_PROVIDERAGENT_BUILD
#ifndef OW_PROVIDERAGENT_API 
#define OW_PROVIDERAGENT_API OW_EXPORT 
#endif
#else
#ifndef OW_PROVIDERAGENT_API 
#define OW_PROVIDERAGENT_API OW_IMPORT 
#endif
#endif

#ifdef OW_OWBI1PROVIFC_BUILD
#ifndef OW_OWBI1PROVIFC_API 
#define OW_OWBI1PROVIFC_API OW_EXPORT 
#endif
#else
#ifndef OW_OWBI1PROVIFC_API 
#define OW_OWBI1PROVIFC_API OW_IMPORT 
#endif
#endif

#ifdef OW_WIN32
#ifndef OW_EXPORT_TEMPLATE 
#define OW_EXPORT_TEMPLATE(API, TMPL, X) template class API TMPL< X > 
#endif
#else
#ifndef OW_EXPORT_TEMPLATE 
#define OW_EXPORT_TEMPLATE(API, TMPL, X) 
#endif
#endif

/* C++ specific stuff here */
#ifdef __cplusplus

/* Need this first macro because ## doesn't expand vars, and we need an intermediate step */
#ifndef OW_NAMESPACE_CAT 
#define OW_NAMESPACE_CAT(ow, ver) ow ## ver 
#endif
#ifndef OW_NAMESPACE_AUX 
#define OW_NAMESPACE_AUX(ver) OW_NAMESPACE_CAT(OpenWBEM, ver) 
#endif
#ifndef OW_NAMESPACE 
#define OW_NAMESPACE OW_NAMESPACE_AUX(OW_OPENWBEM_LIBRARY_VERSION) 
#endif

/* This is so this particular code is only active in OW_config.h, not OWBI1_config.h */
#ifdef OW_NAMESPACE
/* need this to set up an alias. */
namespace OW_NAMESPACE
{
}

namespace OpenWBEM = OW_NAMESPACE;
#endif

#ifdef OW_DEBUG_MEMORY
#include "OW_MemTracer.hpp"
#endif



#endif /* #ifdef __cplusplus */

 
/* __SRC_COMMON_OW_CONFIG_H */
#endif
